title: CSS Arts Gallery
author: Glanshima
email: glanshima@@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a collection of some beautiful CSS Arts.
theme: minima

# social links
twitter_username: glanshima # DO NOT include the @ character, or else the build will fail!
github_username:  glanshima # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
